"""baseline schema

Revision ID: a87d7dc37c33
Revises: 
Create Date: 2026-01-02 15:45:01.137231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a87d7dc37c33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('USER','COACH','ADMIN')", name='ck_account_role'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_account_email'), 'account', ['email'], unique=True)
    op.create_table('admin_profile',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('coach_profile',
    sa.Column('coach_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('birth_month', sa.Integer(), nullable=True),
    sa.Column('birth_day', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("gender IN ('Male','Female','Other','Prefer not to say')", name='ck_coach_profile_gender'),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('coach_id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_profile',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('current_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('birth_month', sa.Integer(), nullable=True),
    sa.Column('birth_day', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("gender IN ('Male','Female','Other','Prefer not to say')", name='ck_user_profile_gender'),
    sa.CheckConstraint('current_weight IS NULL OR current_weight > 0', name='ck_user_profile_current_weight_positive'),
    sa.CheckConstraint('goal_weight IS NULL OR goal_weight > 0', name='ck_user_profile_goal_weight_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('coach_availability',
    sa.Column('availability_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('start_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date_time > start_date_time', name='ck_coach_availability_end_after_start'),
    sa.ForeignKeyConstraint(['coach_id'], ['coach_profile.coach_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('availability_id')
    )
    op.create_index(op.f('ix_coach_availability_coach_id'), 'coach_availability', ['coach_id'], unique=False)
    op.create_table('location',
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_name', sa.String(length=100), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_capacity > 0', name='ck_location_max_capacity_positive'),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_profile.admin_id'], ),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('wellness_session',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_kind', sa.String(length=10), nullable=False),
    sa.Column('start_date_time', sa.DateTime(), nullable=False),
    sa.Column('end_date_time', sa.DateTime(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("(session_kind = 'HABIT' AND user_id IS NOT NULL) OR (session_kind = 'GROUP' AND user_id IS NULL)", name='ck_wellness_session_user_by_kind'),
    sa.CheckConstraint("session_kind IN ('HABIT','GROUP')", name='ck_wellness_session_kind'),
    sa.CheckConstraint('end_date_time > start_date_time', name='ck_wellness_session_end_after_start'),
    sa.CheckConstraint('max_capacity > 0', name='ck_wellness_session_max_capacity_positive'),
    sa.ForeignKeyConstraint(['coach_id'], ['coach_profile.coach_id'], ),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_profile.admin_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('commitment',
    sa.Column('commitment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PLANNED','COMPLETED','MISSED','CANCELED')", name='ck_commitment_status'),
    sa.ForeignKeyConstraint(['session_id'], ['wellness_session.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('commitment_id'),
    sa.UniqueConstraint('user_id', 'session_id', name='uq_commitment_user_session')
    )
    op.create_index(op.f('ix_commitment_session_id'), 'commitment', ['session_id'], unique=False)
    op.create_index(op.f('ix_commitment_user_id'), 'commitment', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commitment_user_id'), table_name='commitment')
    op.drop_index(op.f('ix_commitment_session_id'), table_name='commitment')
    op.drop_table('commitment')
    op.drop_table('wellness_session')
    op.drop_table('location')
    op.drop_index(op.f('ix_coach_availability_coach_id'), table_name='coach_availability')
    op.drop_table('coach_availability')
    op.drop_table('user_profile')
    op.drop_table('coach_profile')
    op.drop_table('admin_profile')
    op.drop_index(op.f('ix_account_email'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
